import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter } from "next/font/google";

import Footer from "@/ui-shared/components/footer/Footer";
import Navbar from "@/ui-shared/components/navbar/Navbar";
import Sidebar from "@/ui-shared/components/sidebar/Sidebar";
import { useAuth } from "@/hooks/auth";
import styles from "./styles.module.css";
import "@/ui-shared/styles/globals.css";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tennis Tournament",
  description: "Generated by Tennis Tournament",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const token = cookieStore.get("token");
  const { isAuthenticated, user } = useAuth({ token: token?.value });

  if (!isAuthenticated) {
    return redirect("/login");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <div className={styles.menu}>
            <Sidebar user={user} />
          </div>
          <div className={styles.content}>
            <Navbar />
            <div className={styles.main}>
              {children}
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
