import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

import { useAuth } from "@/hooks/auth";
import styles from "./styles.module.css";
import "@/ui-shared/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tennis Tournament",
  description: "Generated by Tennis Tournament",
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const token = cookieStore.get("token");
  const { isAuthenticated, user } = useAuth({ token: token?.value });

  if (!isAuthenticated) {
    return redirect("/login");
  }
  if (user?.isAdmin) {
    return redirect("/dashboard");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
